{% set name = "certifi" %}
{% set version = "2026.07.22" %}
{% set normalized_version = ".".join(version.split(".") | map("int") | map("string")) %}

package:
  name: {{ name }}
  version: {{ normalized_version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ normalized_version }}.tar.gz
  sha256: 741e2c3b351ddf169a738da9f2c048608ff7f2c5cc02f1ebc6b118bb090d5d55

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools >=42.0.0
    - wheel
  run:
    - python
    - pip

test:
  source_files:
    - certifi/tests
  imports:
    - certifi
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ normalized_version }}')"
    - pytest -vv certifi/tests

about:
  home: https://certifi.io
  license: MPL-2.0
  license_file: LICENSE
  license_family: Other
  summary: Python package for providing Mozilla's CA Bundle.
  description: |
    Certifi is a curated collection of Root Certificates for validating the
    trustworthiness of SSL certificates while verifying the identity of TLS
    hosts.
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  dev_url: https://github.com/certifi/python-certifi

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - sigmavirus24
    - ocefpaf
    - mingwandroid

