{% set name = "certifi" %}
{% set version = "2025.8.3" %}

{% set pip_version = "24.3.1" %}
{% set setuptools_version = "75.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/certifi-{{ version }}.tar.gz
    sha256: e564105f78ded564e3ae7c923924435e1daa7463faeab5bb932bc53ffae63407

    # tests and tests data files
  - url: https://github.com/certifi/python-certifi/archive/refs/tags/2025.08.03.zip
    sha256: 031c3f1771fcd3d351af44982e05db1df2300df54a0cd9d0d22015a194c0f01b
    folder: {{ name }}

  # bootstrap pip and setuptools to avoid circular dependency
  # but without losing metadata
  # Please note when using conda-build locally, may get following error: certifi cannot depend on itself
  # Try pushing and refer to Prefect logs
  - url: https://pypi.io/packages/py3/p/pip/pip-{{ pip_version }}-py3-none-any.whl
    sha256: 3790624780082365f47549d032f3770eeb2b1e8bd1f7b2e02dace1afa361b4ed
    folder: pip_wheel
  - url: https://pypi.io/packages/py3/s/setuptools/setuptools-{{ setuptools_version }}-py3-none-any.whl
    sha256: ce74b49e8f7110f9bf04883b730f4765b774ef3ef28f722cce7c273d253aaf7d
    folder: setuptools_wheel

build:
  number: 0
  skip: True  # [py<37]

requirements:
  host:
    - python
    - setuptools >=42.0.0
    - wheel
    - pip
  run:
    - python

test:
  source_files:
    - {{ name }}
  imports:
    - certifi
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - python -m unittest discover -s {{ name }}

about:
  home: https://certifi.io
  license: MPL-2.0
  license_file: LICENSE
  license_family: OTHER
  summary: Python package for providing Mozilla's CA Bundle
  description: |
    Certifi provides Mozilla's carefully curated collection of Root Certificates 
    for validating the trustworthiness of SSL certificates while verifying 
    the identity of TLS hosts
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  dev_url: https://github.com/certifi/python-certifi

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - sigmavirus24
    - ocefpaf
    - mingwandroid
