{% set version = "2023.5.7" %}

{% set pip_version = "23.1.2" %}
{% set setuptools_version = "67.8.0" %}

package:
  name: certifi
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/c/certifi/certifi-{{ version }}.tar.gz
    sha256: 0f0d56dc5a6ad56fd4ba36484d6cc34451e1c6548c61daad8c320169f91eddc7
    folder: certifi
  # bootstrap pip and setuptools to avoid circular dependency
  # but without losing metadata
  # Please note when using conda-build locally, may get following error: certifi cannot depend on itself
  # Try pushing and refer to Prefect logs
  - url: https://pypi.io/packages/py3/p/pip/pip-{{ pip_version }}-py3-none-any.whl
    sha256: 3ef6ac33239e4027d9a5598a381b9d30880a1477e50039db2eac6e8a8f6d1b18
    folder: pip_wheel
  - url: https://pypi.io/packages/py3/s/setuptools/setuptools-{{ setuptools_version }}-py3-none-any.whl
    sha256: 5df61bf30bb10c6f756eb19e7c9f3b473051f48db77fddbe06ff2ca307df9a6f
    folder: setuptools_wheel

build:
  number: 0
  skip: True  # [py<36]

requirements:
  host:
    - python
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - certifi

about:
  home: https://certifi.io/
  license: MPL-2.0
  license_file: certifi/LICENSE
  license_family: Other
  summary: Python package for providing Mozilla's CA Bundle.
  description: |
    Certifi is a curated collection of Root Certificates for validating the
    trustworthiness of SSL certificates while verifying the identity of TLS
    hosts.
  doc_url: https://github.com/certifi/python-certifi/blob/master/README.rst
  dev_url: https://github.com/certifi/python-certifi

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - sigmavirus24
    - ocefpaf
    - mingwandroid
