{% set version = "2016.8.2" %}

package:
  name: certifi
  version: {{ version }}

source:
  fn: certifi-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/certifi/certifi-{{ version }}.tar.gz
  sha256: 65ddc34fd9c8509851031d7075b8325393b87e6dbe5875a723959a20266d7a41

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - certifi

about:
  home: http://certifi.io/
  license: ISC
  summary: Python package for providing Mozilla's CA Bundle.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - sigmavirus24
    - ocefpaf
